---
title: VDS Upcoming Races
author: hekker
output:
  html_document:
    toc: true
    theme: spacelab
date: "`r format(Sys.time())`"
---

```{r setup, include=FALSE}
library(dplyr)
library(jsonlite)
library(lubridate)
library(knitr)
library(ggplot2)
theme_set(theme_bw())

knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
load_race <- function(fn) {
    ll <- fromJSON(fn)
    bind_cols(ll$riders,
        race = ll$race,
        start_date = ymd(ll$start_date),
        end_date = ymd(ll$end_date)
    )
}
```

```{r load}
team <- fromJSON("data/team-2023.json") 

team$riders <- team$riders %>%
    mutate(price = as.numeric(price))
team$standings <- team$standings %>%
    mutate(date = ymd_hms(date), position = as.numeric(position))

races <- bind_rows(lapply(Sys.glob("data/startlist-*.json"), load_race))
```

[My Team](https://www.pdcvds.com/myteam.php?mw=1&y=2023)

## Upcoming

```{r upcoming}
inner_join(team$riders, races) %>%
    filter(end_date >= today()) %>%
    select(start_date, race, name, team, price) %>%
    arrange(start_date, race, desc(price)) %>%
    kable()
```

## Ranking

```{r ranking}
team$standings %>%
    arrange(desc(date)) %>%
    head(1) %>%
    kable()
```

```{r ranking_hist}
team$standings %>%
    ggplot(aes(x = date, y = position)) +
    geom_step() +
    ylim(0, 813)
```