---
title: VDS Upcoming Races
date: "`r format(Sys.time())`"
---

```{r setup, include=FALSE}
library(dplyr)
library(jsonlite)
library(lubridate)
library(knitr)
library(ggplot2)
library(stringr)
library(tidyr)
theme_set(theme_bw())
source("_funcs.R")


knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
```

```{r load}
team <- load_team("../data/team-2023.json")
start_lists <- load_races()$start_lists

start_lists <- start_lists %>%
  group_by(race) %>%
  mutate(rank_t = rank / max(rank))

watch <- fromJSON("../watch.json")

start_lists <- start_lists %>%
  filter(end_date >= today())

races <- start_lists %>%
  select(race, start_date, end_date, link) %>%
  unique() %>%
  arrange(start_date)

myteam <- inner_join(team$riders, start_lists %>% select(-team)) %>%
  select(start_date, end_date, race, name, team, rank, rank_t, 
    price, spec, spec_rate) %>%
  mutate(spec = sprintf("%s (%d%%)", spec, spec_rate)) %>%
  select(-spec_rate)

watched <- start_lists %>%
  full_join(watch %>%
    mutate(watched = TRUE)) %>%
  filter(rank <= 10 | watched) %>%
  replace_na(list(watched = FALSE)) %>%
  anti_join(myteam, by = c("name", "race")) %>%
  ungroup()
```

[My Team](https://www.pdcvds.com/myteam.php?mw=1&y=2023)

# Upcoming

```{r calendar, fig.width=12, fig.height=8, dependson=c('load')}
myteam %>%
  mutate(end_date = if_else(start_date == end_date, end_date + 1, end_date)) %>%
  ggplot(aes(x = start_date + hours(1), xend = end_date - hours(1), 
             y = name, yend = name)) +
  geom_segment(aes(size = rank_t)) +
  scale_y_discrete("") +
  scale_x_datetime("") +
  scale_size_binned(range = c(7, .1), n.breaks = 10)
```

```{r upcoming, results="asis", dependson=c('load')}

races %>%
  group_by(start_date, race) %>%
  group_walk(function(t_race, key) {
    tmp_my <- myteam %>%
        filter(race == t_race$race)

    cat(sprintf("## [%s](%s) %s (%d)\n",
      str_trunc(t_race$race, 25),
      t_race$link,
      format(t_race$start_date, "%a, %d.%m"),
      nrow(tmp_my))
    )
    cat("- ", t_race$race, "\n")
    cat("- ", sprintf("%s",
      if_else(t_race$start_date == t_race$end_date,
        as.character(t_race$start_date),
        sprintf("%s - %s", t_race$start_date, t_race$end_date)
      )
    ), "\n")

    cat("\n### My Team\n")
    if (nrow(tmp_my) > 0) {
      print(tmp_my %>%
          select(-race, -start_date, -end_date, -rank_t) %>%
          arrange(rank) %>%
          kable()
      )
    } else {
      cat("*no one*\n")
    }

    cat("\n### Others\n")

    tmp_watched <- watched %>%
        filter(race == t_race$race)
    if (nrow(tmp_watched) > 0) {
      print(tmp_watched %>%
          mutate(watched = if_else(watched, "**", "")) %>%
          select(name, team, rank, watched) %>%
          arrange(rank, team, name) %>%
          kable()
      )
    } else {
      cat("*no one*\n\n")
    }

    cat("\n----\n\n")
}, .keep = TRUE)

```
