when:
  - event: push
    branch: [master,sqlize]
steps:
- name: bauhaus
  image: woodpeckerci/plugin-docker-buildx
  settings:
      password:
        from_secret: pkg push
      username: hekker
      tags: 
      - latest
      registry: repo.testha.se