when:
  - event: push
    branch: [master,sqlize]
steps:
- name: bauhaus
  image: woodpeckerci/plugin-docker-buildx
  settings:
      auto_tag: true
      tags_file: .tags
      password:
        from_secret: pkg push
      username: hekker
      registry: repo.testha.se