when:
  - event: push
    branch: [master,sqlize]
steps:
- name: bauhaus
  privileged: true
  image: woodpeckerci/plugin-docker-buildx
  settings:
      auto_tag: true
      tag: latest
      password:
        from_secret: pkg push
      username: hekker
      registry: repo.testha.se